# https://github.com/actions/labeler

# In some configurations (like Release Drafter), regex is enclosed with slashes (e.g., /build\/.+/), which signifies the start and end of the regular expression.
# However, in GitHub Actions' labeler.yml, you do not need to wrap your regex patterns in slashes. The tool expects just the regex itself, without the delimiters.

feature:
- head-branch: ['^feat/'] # Matches branch names starting with 'feat/'

bugfix:
- head-branch: ['^fix/'] # Matches branch names starting with 'fix/'

documentation:
- head-branch: ['^docs/']

style:
- head-branch: ['^style/']

refactor:
- head-branch: ['^refactor/']

test:
- head-branch: ['^test/']

chore:
- head-branch: ['^chore/']

performance:
- head-branch: ['^perf/']

ci:
- head-branch: ['^ci/']

build:
- head-branch: ['^build/']

revert:
- head-branch: ['^revert/']
