// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Vertical.Slice.Template.ContractTests.KiotaApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IPageListOfUserDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currentEndIndex property</summary>
        public int? CurrentEndIndex { get; set; }
        /// <summary>The currentPageSize property</summary>
        public int? CurrentPageSize { get; set; }
        /// <summary>The currentStartIndex property</summary>
        public int? CurrentStartIndex { get; set; }
        /// <summary>The hasNext property</summary>
        public bool? HasNext { get; set; }
        /// <summary>The hasPrevious property</summary>
        public bool? HasPrevious { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.UserDto>? Items { get; set; }
#nullable restore
#else
        public List<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.UserDto> Items { get; set; }
#endif
        /// <summary>The pageNumber property</summary>
        public int? PageNumber { get; set; }
        /// <summary>The pageSize property</summary>
        public int? PageSize { get; set; }
        /// <summary>The totalCount property</summary>
        public int? TotalCount { get; set; }
        /// <summary>The totalPages property</summary>
        public int? TotalPages { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.IPageListOfUserDto"/> and sets the default values.
        /// </summary>
        public IPageListOfUserDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.IPageListOfUserDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.IPageListOfUserDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.IPageListOfUserDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentEndIndex", n => { CurrentEndIndex = n.GetIntValue(); } },
                { "currentPageSize", n => { CurrentPageSize = n.GetIntValue(); } },
                { "currentStartIndex", n => { CurrentStartIndex = n.GetIntValue(); } },
                { "hasNext", n => { HasNext = n.GetBoolValue(); } },
                { "hasPrevious", n => { HasPrevious = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.UserDto>(global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.UserDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pageNumber", n => { PageNumber = n.GetIntValue(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
                { "totalPages", n => { TotalPages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentEndIndex", CurrentEndIndex);
            writer.WriteIntValue("currentPageSize", CurrentPageSize);
            writer.WriteIntValue("currentStartIndex", CurrentStartIndex);
            writer.WriteBoolValue("hasNext", HasNext);
            writer.WriteBoolValue("hasPrevious", HasPrevious);
            writer.WriteCollectionOfObjectValues<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.UserDto>("items", Items);
            writer.WriteIntValue("pageNumber", PageNumber);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteIntValue("totalCount", TotalCount);
            writer.WriteIntValue("totalPages", TotalPages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
