// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using Vertical.Slice.Template.ContractTests.KiotaApiClient.Models;
namespace Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/users{?Filters*,PageNumber*,PageSize*,SortOrder*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/users{?Filters*,PageNumber*,PageSize*,SortOrder*}", rawUrl)
        {
        }
        /// <summary>
        /// Get users by page endpoint
        /// </summary>
        /// <returns>A <see cref="global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.GetUsersByPageResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.GetUsersByPageResponse?> GetAsync(Action<RequestConfiguration<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.GetUsersByPageResponse> GetAsync(Action<RequestConfiguration<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.GetUsersByPageResponse>(requestInfo, global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Models.GetUsersByPageResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get users by page endpoint
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Vertical.Slice.Template.ContractTests.KiotaApiClient.Api.V1.Users.UsersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get users by page endpoint
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UsersRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Filters { get; set; }
#nullable restore
#else
            public string Filters { get; set; }
#endif
            public int? PageNumber { get; set; }
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? SortOrder { get; set; }
#nullable restore
#else
            public string SortOrder { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
