# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# https://github.com/rhysd/actionlint

name: Build-Test

on:
  push:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "8.0.*"

jobs:
  pre-checks:
    name: Pre-checks (Format, Style, Analyzers, Spelling, Commitlint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

        # npm install, runs `prepare` script automatically in the initialize step
      - name: Install NPM Dependencies
        run: npm install

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Check Conventional Commits
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
            npx commitlint --from $BASE_SHA --to $HEAD_SHA --verbose
          else
            echo "Not a pull request event. Skipping Conventional Commits check."
          fi

      - name: Run Format Task
        run: npm run format

      - name: Run Style Task
        run: npm run style

      - name: Run Analyzers Task
        run: npm run analyzers

      - name: Run Spelling Task
        run: npm run spell

  build-test:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore dependencies
        run: dotnet restore Vertical.Slice.Template.sln

      - name: Build Version
        run: dotnet build Vertical.Slice.Template.sln -c Release --no-restore

      - name: Test Version
        run: |
          dotnet test Vertical.Slice.Template.sln  -c Release --no-restore  --no-build
