name: Release Drafter Auto Labeler
on:
  # pull_request event is required for autolabeler
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  auto-labeler:
    name: Release drafter Auto Labeler
    runs-on: ubuntu-latest
    permissions:
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-releaser: true # releaser mode is disabled.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
