name: Release Drafter Auto Labeler
on:
  # pull_request event is required for autolabeler
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  auto-labeler:
    name: Release drafter Auto Labeler
    runs-on: ubuntu-latest
    permissions:
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
      contents: read

    steps:
      - name: Apply labels based on PR title and branch name
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # - uses: release-drafter/release-drafter@v6
      #   with:
      #     config-name: release-drafter.yml
      #     disable-releaser: true # releaser mode is disabled.
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
