name: Auto Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited

jobs:
  auto-labeler:
    name: Auto Labeler
    runs-on: ubuntu-latest
    permissions:
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
      contents: read
      statuses: write
      checks: write

    steps:
      # - name: Apply labels based on PR title and branch name
      #   uses: actions/labeler@v5
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     configuration-path: ".github/labeler.yml"

      # - uses: release-drafter/release-drafter@v6
      #   with:
      #     config-name: release-drafter.yml
      #     disable-releaser: true # releaser mode is disabled.
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: fuxingloh/multi-labeler@v1
        name: conventional-commits-pull-request-labeler
        with:
          github-token: ${{secrets.GITHUB_TOKEN}} # optional, default to '${{ github.token }}'
          config-path: .github/multi-labeler.yml # optional, default to '.github/labeler.yml'

      - name: check-conventional-commits-labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        if: success()
        with:
          any_of: feature,bug,enhancement,refactor,deprecated,security,documentation,build,ci/cd,chore,performance,formatting,dependencies,test,major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
