name: Release Drafter Auto Labeler
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  auto-labeler:
    name: Release drafter Auto Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-releaser: true # only run auto-labeler for PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
